name: Test

on:
  push:
    tags-ignore:
      - v[0-9]+.[0-9]+.[0-9]+
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  code_style:
    name: Code style
    uses: './.github/workflows/code_style.yml'
  unit_tests:
    name: Unit tests
    needs: code_style
    uses: './.github/workflows/unit_tests.yml'
    with:
      testing: true
  code_security:
    name: Code security scan
    needs: unit_tests
    uses: './.github/workflows/codeql.yml'